name = "mterminal-marketplace"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_CLIENT_ID = "replace-me"
PUBLIC_R2_BASE = "http://localhost:8787/r2"
SIGNED_URL_TTL_SEC = "300"
ADMIN_LOGINS = "arthurr0"
ADMIN_GITHUB_CLIENT_ID = "replace-me"
ADMIN_DEV_LOGIN = "0"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "mterminal"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "src/db/migrations"

[[r2_buckets]]
binding = "PACKAGES"
bucket_name = "mterminal-packages"

[[kv_namespaces]]
binding = "SESSIONS"
id = "00000000000000000000000000000000"

[assets]
directory = "../admin/dist"
binding = "ASSETS"

[env.staging]
name = "mterminal-marketplace-staging"

[env.staging.vars]
GITHUB_CLIENT_ID = "Iv23liV3HwWsVxbpAooB"
ADMIN_GITHUB_CLIENT_ID = "Iv23litCwpgy09OFcLgn"
ADMIN_LOGINS = "arthurr0"
ADMIN_DEV_LOGIN = "0"
PUBLIC_R2_BASE = "https://staging.marketplace.mterminal.dev/r2"
SIGNED_URL_TTL_SEC = "300"

[[env.staging.routes]]
pattern = "staging.marketplace.mterminal.dev"
custom_domain = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "mterminal-staging"
database_id = "3a2448cd-5fa6-4ff7-8844-bfdb8bea9ea2"
migrations_dir = "src/db/migrations"

[[env.staging.r2_buckets]]
binding = "PACKAGES"
bucket_name = "mterminal-packages-staging"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "4bddec4af8ed454fa4dc44a7c213a7aa"

[env.staging.assets]
directory = "../admin/dist"
binding = "ASSETS"

[env.staging.triggers]
crons = ["*/15 * * * *"]

[env.production]
name = "mterminal-marketplace-prod"

[env.production.vars]
GITHUB_CLIENT_ID = "Iv23lian1lpjtX5PjlYG"
ADMIN_GITHUB_CLIENT_ID = "Iv23li9c8E0Bf2WeohC9"
ADMIN_LOGINS = "arthurr0"
ADMIN_DEV_LOGIN = "0"
PUBLIC_R2_BASE = "https://marketplace.mterminal.dev/r2"
SIGNED_URL_TTL_SEC = "300"

[[env.production.routes]]
pattern = "marketplace.mterminal.dev"
custom_domain = true

[[env.production.d1_databases]]
binding = "DB"
database_name = "mterminal-prod"
database_id = "03971aaa-253a-4910-971f-924045d7f567"
migrations_dir = "src/db/migrations"

[[env.production.r2_buckets]]
binding = "PACKAGES"
bucket_name = "mterminal-packages-prod"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "411640c8c5154ee99efa0115d7be2a36"

[env.production.assets]
directory = "../admin/dist"
binding = "ASSETS"

[env.production.triggers]
crons = ["*/15 * * * *"]
